{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "392b5059-a5dd-4203-8f5d-eb1cf1f1aea6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import scrolledtext, messagebox\n",
    "import joblib\n",
    "import re\n",
    "import numpy as np\n",
    "from scipy.sparse import hstack\n",
    "\n",
    "class SpamClassifierGUI:\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.root.title(\"SMS Spam Classifier\")\n",
    "        self.root.geometry(\"600x500\")\n",
    "        \n",
    "        # Load model\n",
    "        self.load_model()\n",
    "        \n",
    "        # Create GUI elements\n",
    "        self.create_widgets()\n",
    "    \n",
    "    def load_model(self):\n",
    "        try:\n",
    "            self.model = joblib.load('spam_classifier_lr.pkl')\n",
    "            self.vectorizer = joblib.load('tfidf_vectorizer.pkl')\n",
    "            self.feature_cols = joblib.load('feature_columns.pkl')\n",
    "            self.model_loaded = True\n",
    "        except:\n",
    "            self.model_loaded = False\n",
    "    \n",
    "    def create_widgets(self):\n",
    "        # Title\n",
    "        title = tk.Label(self.root, text=\"SMS Spam Classifier\", \n",
    "                         font=(\"Arial\", 20, \"bold\"))\n",
    "        title.pack(pady=10)\n",
    "        \n",
    "        # Instructions\n",
    "        if not self.model_loaded:\n",
    "            warning = tk.Label(self.root, \n",
    "                               text=\"⚠️ Model files not found! Run training first.\",\n",
    "                               fg=\"red\", font=(\"Arial\", 12))\n",
    "            warning.pack(pady=5)\n",
    "        \n",
    "        # Input label\n",
    "        input_label = tk.Label(self.root, text=\"Enter your message:\", \n",
    "                                font=(\"Arial\", 12))\n",
    "        input_label.pack(pady=5)\n",
    "        \n",
    "        # Text input area\n",
    "        self.text_input = scrolledtext.ScrolledText(self.root, \n",
    "                                                    height=8, \n",
    "                                                    width=60,\n",
    "                                                    font=(\"Arial\", 10))\n",
    "        self.text_input.pack(pady=10)\n",
    "        \n",
    "        # Analyze button\n",
    "        analyze_btn = tk.Button(self.root, \n",
    "                                text=\"🔍 Analyze Message\", \n",
    "                                command=self.analyze,\n",
    "                                bg=\"#4CAF50\", \n",
    "                                fg=\"white\",\n",
    "                                font=(\"Arial\", 12, \"bold\"),\n",
    "                                padx=20, pady=10)\n",
    "        analyze_btn.pack(pady=10)\n",
    "        \n",
    "        # Result frame\n",
    "        self.result_frame = tk.Frame(self.root, bd=2, relief=tk.GROOVE)\n",
    "        self.result_frame.pack(pady=20, padx=20, fill=tk.BOTH, expand=True)\n",
    "        \n",
    "        # Result label\n",
    "        self.result_label = tk.Label(self.result_frame, \n",
    "                                      text=\"Result will appear here\",\n",
    "                                      font=(\"Arial\", 14))\n",
    "        self.result_label.pack(pady=10)\n",
    "        \n",
    "        # Confidence label\n",
    "        self.confidence_label = tk.Label(self.result_frame,\n",
    "                                          text=\"\",\n",
    "                                          font=(\"Arial\", 10))\n",
    "        self.confidence_label.pack()\n",
    "        \n",
    "        # Features label\n",
    "        self.features_label = tk.Label(self.result_frame,\n",
    "                                        text=\"\",\n",
    "                                        font=(\"Arial\", 10),\n",
    "                                        justify=tk.LEFT)\n",
    "        self.features_label.pack(pady=5)\n",
    "    \n",
    "    def clean_text(self, text):\n",
    "        text = text.lower()\n",
    "        text = re.sub(r'[^a-zA-Z0-9\\s]', '', text)\n",
    "        text = re.sub(r'\\d+', '', text)\n",
    "        text = re.sub(r'\\s+', ' ', text).strip()\n",
    "        return text\n",
    "    \n",
    "    def extract_features(self, message):\n",
    "        features = {\n",
    "            'contains_urgent': 1 if re.search(r'urgent|urg|asap', message, re.I) else 0,\n",
    "            'contains_winner': 1 if re.search(r'won|winner|win|claim|prize|cash', message, re.I) else 0,\n",
    "            'contains_free': 1 if re.search(r'free|complimentary', message, re.I) else 0,\n",
    "            'contains_call': 1 if re.search(r'call|text|reply', message, re.I) else 0,\n",
    "            'contains_money': 1 if re.search(r'\\$|£|€|pound|dollar', message, re.I) else 0,\n",
    "            'contains_number': 1 if re.search(r'\\d', message) else 0,\n",
    "            'exclamation_count': message.count('!'),\n",
    "            'question_count': message.count('?'),\n",
    "            'capital_ratio': sum(1 for c in message if c.isupper()) / (len(message) + 1)\n",
    "        }\n",
    "        return features\n",
    "    \n",
    "    def analyze(self):\n",
    "        if not self.model_loaded:\n",
    "            messagebox.showerror(\"Error\", \"Model not loaded!\")\n",
    "            return\n",
    "        \n",
    "        # Get message\n",
    "        message = self.text_input.get(\"1.0\", tk.END).strip()\n",
    "        \n",
    "        if not message:\n",
    "            messagebox.showwarning(\"Warning\", \"Please enter a message!\")\n",
    "            return\n",
    "        \n",
    "        # Clean and predict\n",
    "        cleaned = self.clean_text(message)\n",
    "        features = self.extract_features(message)\n",
    "        \n",
    "        # Vectorize\n",
    "        msg_tfidf = self.vectorizer.transform([cleaned])\n",
    "        features_array = np.array([[features[col] for col in self.feature_cols]])\n",
    "        final_features = hstack([msg_tfidf, features_array])\n",
    "        \n",
    "        # Predict\n",
    "        prediction = self.model.predict(final_features)[0]\n",
    "        proba = self.model.predict_proba(final_features)[0]\n",
    "        \n",
    "        # Update UI\n",
    "        if prediction == 1:\n",
    "            self.result_label.config(text=\"🚨 SPAM DETECTED!\", fg=\"red\")\n",
    "            confidence = proba[1]\n",
    "        else:\n",
    "            self.result_label.config(text=\"✅ LEGITIMATE MESSAGE\", fg=\"green\")\n",
    "            confidence = proba[0]\n",
    "        \n",
    "        self.confidence_label.config(text=f\"Confidence: {confidence:.2%}\")\n",
    "        \n",
    "        # Show features\n",
    "        feature_text = \"Spam Indicators:\\n\"\n",
    "        if features['contains_urgent']:\n",
    "            feature_text += \"• Urgent language\\n\"\n",
    "        if features['contains_winner']:\n",
    "            feature_text += \"• Prize/winner language\\n\"\n",
    "        if features['contains_free']:\n",
    "            feature_text += \"• 'Free' offers\\n\"\n",
    "        if features['contains_call']:\n",
    "            feature_text += \"• Call to action\\n\"\n",
    "        if features['contains_money']:\n",
    "            feature_text += \"• Money symbols\\n\"\n",
    "        if features['exclamation_count'] > 2:\n",
    "            feature_text += f\"• {features['exclamation_count']} exclamation marks\\n\"\n",
    "        \n",
    "        self.features_label.config(text=feature_text)\n",
    "\n",
    "# Run the GUI\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    app = SpamClassifierGUI(root)\n",
    "    root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9937b85a-654d-4be9-a03a-50a35c378a46",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
